<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Achat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get achat by achat_id
     */
    function get_achat($achat_id)
    {
        return $this->db->get_where('achats',array('achat_id'=>$achat_id))->row_array();
    }
    
    /*
     * Get all achats count
     */
    function get_all_achats_count()
    {
        $this->db->from('achats');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all achats
     */
    function get_all_achats($params = array())
    {
        $this->db->order_by('achat_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('achats')->result_array();
    }
        
    /*
     * function to add new achat
     */
    function add_achat($params)
    {
        $this->db->insert('achats',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update achat
     */
    function update_achat($achat_id,$params)
    {
        $this->db->where('achat_id',$achat_id);
        return $this->db->update('achats',$params);
    }
    
    /*
     * function to delete achat
     */
    function delete_achat($achat_id)
    {
        return $this->db->delete('achats',array('achat_id'=>$achat_id));
    }
}
