<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Auteur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get auteur by aut_id
     */
    function get_auteur($aut_id)
    {
        return $this->db->get_where('auteurs',array('aut_id'=>$aut_id))->row_array();
    }
    
    /*
     * Get all auteurs count
     */
    function get_all_auteurs_count()
    {
        $this->db->from('auteurs');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all auteurs
     */
    function get_all_auteurs($params = array())
    {
        $this->db->order_by('aut_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('auteurs')->result_array();
    }
        
    /*
     * function to add new auteur
     */
    function add_auteur($params)
    {
        $this->db->insert('auteurs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update auteur
     */
    function update_auteur($aut_id,$params)
    {
        $this->db->where('aut_id',$aut_id);
        return $this->db->update('auteurs',$params);
    }
    
    /*
     * function to delete auteur
     */
    function delete_auteur($aut_id)
    {
        return $this->db->delete('auteurs',array('aut_id'=>$aut_id));
    }
}
