<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Livre_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get livre by liv_id
     */
    function get_livre($liv_id)
    {
        return $this->db->get_where('livres',array('liv_id'=>$liv_id))->row_array();
    }
    
    /*
     * Get all livres count
     */
    function get_all_livres_count()
    {
        $this->db->from('livres');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all livres
     */
    function get_all_livres($params = array())
    {
        $this->db->order_by('liv_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('livres')->result_array();
    }
        
    /*
     * function to add new livre
     */
    function add_livre($params)
    {
        $this->db->insert('livres',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update livre
     */
    function update_livre($liv_id,$params)
    {
        $this->db->where('liv_id',$liv_id);
        return $this->db->update('livres',$params);
    }
    
    /*
     * function to delete livre
     */
    function delete_livre($liv_id)
    {
        return $this->db->delete('livres',array('liv_id'=>$liv_id));
    }

    public function get_catalogue()
    {
    
        $this->db->order_by('livres.liv_id', 'DESC');
        $this->db->join('ouvrages', 'ouvrages.ouv_id = livres.ouvrage_sid');
        $this->db->join('auteurs', 'auteurs.aut_id = ouvrages.auteur_sid');

        $query = $this->db->get('livres');

        if ($query) {
            return $query->result();
        } else {
            return false;
        }
        
    }
}
