<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ouvrage_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ouvrage by ouv_id
     */
    function get_ouvrage($ouv_id)
    {
        return $this->db->get_where('ouvrages',array('ouv_id'=>$ouv_id))->row_array();
    }
    
    /*
     * Get all ouvrages count
     */
    function get_all_ouvrages_count()
    {
        $this->db->from('ouvrages');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ouvrages
     */
    function get_all_ouvrages($params = array())
    {
        $this->db->order_by('ouv_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ouvrages')->result_array();
    }
        
    /*
     * function to add new ouvrage
     */
    function add_ouvrage($params)
    {
        $this->db->insert('ouvrages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ouvrage
     */
    function update_ouvrage($ouv_id,$params)
    {
        $this->db->where('ouv_id',$ouv_id);
        return $this->db->update('ouvrages',$params);
    }
    
    /*
     * function to delete ouvrage
     */
    function delete_ouvrage($ouv_id)
    {
        return $this->db->delete('ouvrages',array('ouv_id'=>$ouv_id));
    }
}
